### ISSUE TITLE
Enhance UI

### ISSUE THREAD

**Issue by shamvi-05** [shamvi-05/MLH_Orientation_Hackathon#2]
- [x] Changing of the template
- [x] Adding Footer
- [x] Change the favicon
- [x] Add a scrolling bar or some alternative
- [x] Fixing footer with proper alignment and links.
- [x] Adding Creators proper description and links

**Comment by V2dha** [comment]
I'll work on creating a landing page with a footer and changing the template

**Comment by ssurbhi560** [comment]
@shamvi-05 @V2dha , I have changed your comment to a checklist this way we could track our progress better. Since Vividha has already completed the first two tasks I have marked them as completed. We can keep adding the new issues that we would like to have for the improved UI here. 
Also, thanks @V2dha, the new UI looks so amazing! :D

**Comment by shamvi-05** [comment]
changed favicon and scrollbar is there.

**Comment by ssurbhi560** [comment]
We should a link to "Explore" page in the header as that's the main feature of our website it should be visible at the top. Let me know what you folks think about this, if this sounds like a good idea I will go ahead and open a PR with this change.

**Comment by V2dha** [comment]
> We should a link to "Explore" page in the header as that's the main feature of our website it should be visible at the top. Let me know what you folks think about this, if this sounds like a good idea I will go ahead and open a PR with this change.

Yes, that makes sense!

**Comment by shamvi-05** [comment]
Since every task is done I will close this issue
